[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.black]
target-version = ['py310']
line-length = 120
exclude = '''
/(
  | \.venv
  | migrations
)/
'''

[tool.pytest.ini_options]
addopts = "-ra --cov=src"
pythonpath = ["src"]
python_files = ["tests.py"]
env_override_existing_values = 1
env_files = [".env", ".env.test"]
